application: fb2goog
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: home.py

- url: /upload
  script: home.py

- url: /index\.html
  script: home.py
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css
  static_dir: static/css

- url: /image/(.*\.(gif|png|jpg))
  static_files: static/image/\1
  upload: static/image/(.*\.(gif|png|jpg))

- url: /.*
  script: 404.html
